#!/usr/bin/env bash
#
# postfix/mayhem/build.sh — build the two OSS-Fuzz harnesses for Postfix (vdukhovni/postfix) as
# sanitized libFuzzer targets (+ standalone reproducers).
#
# Fuzzed surface (attacker-controlled mail bytes parsed by Postfix's own code):
#   fuzz_tok822 — RFC 822 address/token parser: tok822_parse_limit() then internalize/externalize
#                 (src/global/tok822_*.c, src/util/lex_822 path). Drives the address-list lexer that
#                 Postfix runs on every recipient/sender header it rewrites.
#   fuzz_mime   — MIME / message header state machine: mime_state_alloc()+mime_state_update()
#                 (src/global/mime_state.c, header_token.c, is_header.c, header_opts.c) over a raw
#                 message stream — the parser that splits headers/body and enforces 7bit/8bit/encoding
#                 rules on inbound mail.
#
# These harnesses live in the OSS-Fuzz project tree (not in the upstream repo); we vendor them under
# mayhem/harnesses/ and compile them exactly as upstream's projects/postfix/build.sh does.
#
# Build contract comes from the org base ENV (CC/CXX/SANITIZER_FLAGS/LIB_FUZZING_ENGINE/SRC/
# STANDALONE_FUZZ_MAIN). Postfix is built with `make makefiles CCARGS=... && make`; we inject
# $SANITIZER_FLAGS into CCARGS so the PARSER code itself (libglobal/libutil) is instrumented, not
# just the harness wrapper.
set -euo pipefail

# clang rejects SOURCE_DATE_EPOCH='' — must be unset or a valid integer.
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

# `=` (not `:=`) for SANITIZER_FLAGS so an explicit empty --build-arg builds with NO sanitizers.
: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer -g}"

# Debug flags: DWARF-3 symbols for fuzz binaries (spec §6.2 item 10).
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
export DEBUG_FLAGS

# Relax ONE benign UBSan check: postfix's msg_output.c iterates `mp < msg_out_info + count` where
# msg_out_info is NULL and count is 0 on the very first call (msg_buffers[] / msg_output() setup that
# every harness triggers via msg_vstream_init). That is a "applying zero offset to null pointer"
# (pointer-overflow) report — well-defined in practice, not a memory bug — but it fires on the FIRST
# input and aborts (-fno-sanitize-recover), so the fuzzer can never iterate. Drop only that sub-check;
# ASan + the rest of UBSan stay halting. (Only added when SANITIZER_FLAGS actually requests UBSan.)
case "${SANITIZER_FLAGS:-}" in
  *undefined*) SANITIZER_FLAGS="$SANITIZER_FLAGS -fno-sanitize=pointer-overflow" ;;
esac
: "${CC:=clang}" ; : "${CXX:=clang++}" ; : "${LIB_FUZZING_ENGINE:=-fsanitize=fuzzer}"
: "${STANDALONE_FUZZ_MAIN:=/opt/mayhem/StandaloneFuzzTargetMain.c}"
: "${MAYHEM_JOBS:=$(nproc)}"
export SANITIZER_FLAGS CC CXX LIB_FUZZING_ENGINE MAYHEM_JOBS

# Postfix source lives in the `postfix/` subdir of vdukhovni/postfix (matches upstream build.sh).
PF="$SRC/postfix"
HARNESS_DIR="$SRC/mayhem/harnesses"
cd "$PF"

# ── 1) Build Postfix WITH sanitizers so the fuzzed parsers are instrumented ───────────────────────
# Coverage feedback: add -fsanitize=fuzzer-no-link to the LIBRARY build so the parser objects carry
# SanitizerCoverage edges (libFuzzer links the real runtime into the harness binary later).
# The -D defines mirror upstream projects/postfix/build.sh's harness compile flags so the headers
# expand the same way (NO_NIS / NO_EAI / static maps / SNAPSHOT).
CCARGS="${SANITIZER_FLAGS} ${DEBUG_FLAGS} -fsanitize=fuzzer-no-link \
  -DHAS_DEV_URANDOM -DSNAPSHOT -UUSE_DYNAMIC_LIBS -DDEF_SHLIB_DIR=\"no\" \
  -UUSE_DYNAMIC_MAPS -DNO_EAI -DDEF_SMTPUTF8_ENABLE=\"no\" \
  -DNO_NIS -DNO_NISPLUS -Wno-comment -fno-common"

# `make tidy` first so a re-run (cron rebuild) doesn't link stale non-instrumented objects.
make tidy >/dev/null 2>&1 || true
make makefiles CC="$CC" CCARGS="$CCARGS"
make -j"$MAYHEM_JOBS"
echo ">> postfix built; libs:" && ls -la lib/libglobal.a lib/libutil.a

# Harness compile flags: same set, used for the harness translation units.
HCC="-DHAS_DEV_URANDOM -DSNAPSHOT -UUSE_DYNAMIC_LIBS -DDEF_SHLIB_DIR=\"no\" \
     -UUSE_DYNAMIC_MAPS -DNO_EAI -DDEF_SMTPUTF8_ENABLE=\"no\" \
     -DLINUX4 -Wformat -Wno-comment -fno-common"

BUILD="$PF/mayhem-build"
mkdir -p "$BUILD"

# Standalone (run-once, no libFuzzer runtime) driver object — shared by both harnesses.
$CC $SANITIZER_FLAGS $DEBUG_FLAGS -c "$STANDALONE_FUZZ_MAIN" -o "$BUILD/standalone_main.o"

# ── 2) Compile + link each harness twice: libFuzzer (-> /mayhem/<name>) + standalone reproducer ───
# include paths mirror upstream: -I src/global (the .c dir) and -I include (generated by make).
build_one() {
  local name="$1"           # e.g. fuzz_tok822
  local incdir="$2"         # dir of the harness's local headers (.h alongside .c sources)
  echo ">> building $name"

  # eval so the quoted -D"no" string survives word-splitting exactly like upstream's build.sh.
  eval $CC $SANITIZER_FLAGS $DEBUG_FLAGS -fsanitize=fuzzer-no-link $HCC \
        -I"$incdir" -I"$PF/include" \
        -c "$HARNESS_DIR/$name.c" -o "$BUILD/$name.o"

  # libFuzzer target -> /mayhem/<name>
  $CXX $SANITIZER_FLAGS $DEBUG_FLAGS $LIB_FUZZING_ENGINE "$BUILD/$name.o" \
      "$PF/lib/libglobal.a" "$PF/lib/libutil.a" -ldb -lm -lpthread \
      -o "/mayhem/$name"

  # standalone reproducer (no libFuzzer runtime) -> /mayhem/<name>-standalone
  $CXX $SANITIZER_FLAGS $DEBUG_FLAGS "$BUILD/$name.o" "$BUILD/standalone_main.o" \
      "$PF/lib/libglobal.a" "$PF/lib/libutil.a" -ldb -lm -lpthread \
      -o "/mayhem/$name-standalone"

  echo "built $name (+ standalone)"
}

build_one fuzz_tok822 "$PF/src/global"
build_one fuzz_mime   "$PF/src/global"

echo "build.sh complete:"
ls -la /mayhem/fuzz_tok822 /mayhem/fuzz_mime \
       /mayhem/fuzz_tok822-standalone /mayhem/fuzz_mime-standalone 2>&1 || true
